### PR TITLE
Add NYT clone using CSS positioning and semantic HTML elements

### PR DESCRIPTION
**Pull request by rotimiazeez**
# Positioning and Floating Element 🎉 

> This PR adds a project that illustrates the layout of the page's basic structure using empty semantic HTML elements that are appropriately sized and positioned with CSS.

Additional description of the project and its features.

## Built With ❤️ 

- HTML
- CSS
- Stylelint, Github Actions

## Deployed Preview 🚀 

[Deployed Preview Link](https://deploy-preview-1--harzeyzh-nyt-clone.netlify.app/)

## Note to code reviewer 😉 

1. Please note that since the project is not a responsive one kindly use the screen-size of width within `{1285-1366}px`.
2. The live demo link on the readme is for the main branch, hence not yet deployed until it is merged. Kindly use [this deployed preview](https://deploy-preview-1--harzeyzh-nyt-clone.netlify.app/) (also attached above).

<details>
    <summary>Click here to see full screenshot</summary>

Full Screenshot

</details>

### CODE REVIEW

**Comment by descholar-ceo** [comment]
# This Pull Request is under review by [descholar-ceo](https://github.com/descholar-ceo) :eyes: :eyes: 
## Please wait a bit ...

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @rotimiazeez  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks like the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimal requirements of this project, keep it up, and your project is really almost done.
:+1: This project is one of the great projects I have ever seen at the first submission, you have done a splendid job.
#### :warning: However we need to make few changes to mark this project approved. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [ ] Your CSS codes should always be DRY (Don't Repeat Yourself), you have some CSS codes which are being repeated several times, I have extracted some of them but not all of them, read them down:
```css
padding-top: 16px; /* => repeated 3 times */
font-size: 80%; /* => repeated 2 times */
border-bottom: 1px solid rgb(226, 226, 226); /* => repeated 3 times */
font-family: helvetica, arial, sans-serif; /* => repeated 3 times */
```
There are some other repeated codes, please look for all of them and fix that repetition issue.

:point_right: As a peace of advice, please use utility classes, or group elements which have the same properties, style them together. Here is a great [article to read](https://vanseodesign.com/css/dry-principles/) which will help you to know how to keep your CSS DRY
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by rotimiazeez** [comment]
Hi, @descholar-ceo thanks for the review. :wave:

I have made all changes as suggested however, I skipped one of the properties because it only appeared twice and I don't want to create a new class for that alone. I understand that this method is more suitable for larger apps and I'll put that in mind In
my future projects. Thanks 🙂

**Review by smcommits — APPROVED** [review]
# Status: Approved :+1: 
## Hello, @rotimiazeez! You have done a great job. Nice work implementing the changes requested by the previous TSE. This PR is now approved. You can go ahead and merge the branch. Congratulations and good luck with your next project.

**Pull request merged**
